---
title: "Regression with IV: Elderly_pct"
author: Kanta Ogawa
date: "2022 / 03 / 13"
output: html_document
---


```{r read data, echo=FALSE, include=FALSE}
library(dplyr)
library(tidyr)
library(sandwich)
library(lmtest)
library(AER)
library(ggmap)
library(stargazer)
library(readr)
library(xtable)
library(ggplot2)
library(ivmodel)
# library(Hmisc)

df <- read.csv("../Data/panel_data.csv")
```

```{r, echo=FALSE, include=FALSE}


# 1. GINI -Grants

df_unbalance_redist_grants <- df[!is.na(df$Relative_redistributive_effects) &
  !is.na(df$Grants_by_private_agencies_and_NGOs) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Welfare_exp), ]

df_unbalance_redist_grants_count <- df_unbalance_redist_grants %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_redist_grants_one <- df_unbalance_redist_grants_count[df_unbalance_redist_grants_count$count == 1, ]

for (i in df_unbalance_redist_grants_one$LOCATION) {
  df_unbalance_redist_grants <- df_unbalance_redist_grants[df_unbalance_redist_grants$LOCATION != i, ]
}

df_unbalance_redist_grants_timecount <- df_unbalance_redist_grants %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK


###### pattern 1-Elderly_pct

ivreg_unbalance_rel_redist_grants_1 <- ivreg(Grants_by_private_agencies_and_NGOs ~ 1 + Relative_redistributive_effects
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Estonia
  + Finland
  + Germany
  + Ireland
  + Italy
  + New_Zealand
  + Portugal
  + Republic_of_Korea
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 14 countries
  + y2005 # omit y2004
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + y2019 |
  . - Relative_redistributive_effects
    + Elderly_pct,
data = df_unbalance_redist_grants
)

GINI_1_1 <- coeftest(ivreg_unbalance_rel_redist_grants_1, vcov = vcovHC, type = "HC3")



# abonrmal!!
Y_1 <- df_unbalance_redist_grants[, "Grants_by_private_agencies_and_NGOs"]
D_1 <- df_unbalance_redist_grants[, "Relative_redistributive_effects"]
Z_1 <- df_unbalance_redist_grants[, "Elderly_pct"]
Xname_1 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
   "y2005",
  "y2006",
  "y2007",
  "y2008",
  "y2009",
  "y2010",
  "y2011",
  "y2012",
  "y2013",
  "y2014",
  "y2015",
  "y2016",
  "y2017",
  "y2018",
  "y2019"
)

X_1 <- df_unbalance_redist_grants[, Xname_1]

GINI_1_1_iv <- ivmodel(Y = Y_1, D = D_1, Z = Z_1, X = X_1)
GINI_1_1_test <- AR.test(GINI_1_1_iv)

GINI_1_1_LIML <- LIML(GINI_1_1_iv)



# 2. GINI - log_Private


df_unbalance_redist_priv <- df[!is.na(df$Relative_redistributive_effects) &
  !is.na(df$log_Private_transfer) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Right_left), ]

df_unbalance_redist_priv_count <- df_unbalance_redist_priv %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_redist_priv_one <- df_unbalance_redist_priv_count[df_unbalance_redist_priv_count$count == 1, ]

for (i in df_unbalance_redist_priv_one$LOCATION) {
  df_unbalance_redist_priv <- df_unbalance_redist_priv[df_unbalance_redist_priv$LOCATION != i, ]
}

df_unbalance_redist_priv_timecount <- df_unbalance_redist_priv %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_redist_priv_timeone <- df_unbalance_redist_priv_timecount[df_unbalance_redist_priv_timecount$timecount == 1, ]


for (t in df_unbalance_redist_priv_timeone$TIME) {
  df_unbalance_redist_priv <- df_unbalance_redist_priv[df_unbalance_redist_priv$TIME != t, ]
}


###### pattern 1 - Elderly_pct
ivreg_unbalance_rel_redist_priv_1 <- ivreg(log_Private_transfer ~ 1
+ Relative_redistributive_effects
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Lithuania
  + Luxembourg
  + Mexico
  + New_Zealand
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 25 countries
  + y2005 # omit y2004
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018 |
  . - Relative_redistributive_effects
    + Elderly_pct,
data = df_unbalance_redist_priv
)


GINI_2_1 <- coeftest(ivreg_unbalance_rel_redist_priv_1, vcov = vcovHC, type = "HC3")





# abornmal AR test




Y_2 <- df_unbalance_redist_priv[, "log_Private_transfer"]
D_2 <- df_unbalance_redist_priv[, "Relative_redistributive_effects"]
Z_2 <- df_unbalance_redist_priv[, "Elderly_pct"]
Xname_2 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
  "y2005", # omit y2004
  "y2006",
  "y2007",
  "y2008",
  "y2009",
  "y2010",
  "y2011",
  "y2012",
  "y2013",
  "y2014",
  "y2015",
  "y2016",
  "y2017",
  "y2018"
)

X_2 <- df_unbalance_redist_priv[, Xname_2]

#GINI_2_1_iv <- ivmodel(Y = Y_2, D = D_2, Z = Z_2, X = X_2)
#GINI_2_1_test <- AR.test(GINI_2_1_iv)

#GINI_2_1_LIML <- LIML(GINI_2_1_iv)




# 3. GINI - WGI


df_unbalance_redist_WGI <- df[!is.na(df$Relative_redistributive_effects) &
  !is.na(df$Giving_money) &
  (df$Giving_money != "") &
  (df$Giving_money != "-") &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Unemployment_rate_pct), ]

df_unbalance_redist_WGI <- df_unbalance_redist_WGI[df_unbalance_redist_WGI$Giving_money != "", ]

df_unbalance_redist_WGI_count <- df_unbalance_redist_WGI %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_redist_WGI_one <- df_unbalance_redist_WGI_count[df_unbalance_redist_WGI_count$count == 1, ]

for (i in df_unbalance_redist_WGI_one$LOCATION) {
  df_unbalance_redist_WGI <- df_unbalance_redist_WGI[df_unbalance_redist_WGI$LOCATION != i, ]
}

df_unbalance_redist_WGI_timecount <- df_unbalance_redist_WGI %>%
  group_by(TIME) %>%
  summarise(timecount = n())

df_unbalance_redist_WGI_timeone <- df_unbalance_redist_WGI_timecount[df_unbalance_redist_WGI_timecount$TIME == 1, ]

for (t in df_unbalance_redist_WGI_timeone$TIME) {
  df_unbalance_redist_WGI <- df_unbalance_redist_WGI[df_unbalance_redist_WGI$TIME != t, ]
}



###### pattern1 - Elederly_pct

ivreg_unbalance_rel_redist_WGI_1 <- ivreg(Giving_money ~ 1 + Relative_redistributive_effects
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Mexico
  + New_Zealand
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Turkey
  + United_Kingdom
  + United_States_of_America # 22 countries
  + y2011 # remove y2010  -9 years-
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018 |
  . - Relative_redistributive_effects
    + Elderly_pct,
data = df_unbalance_redist_WGI
)

GINI_3_1 <- coeftest(ivreg_unbalance_rel_redist_WGI_1, vcov = vcovHC, type = "HC3") # revise


# abonrmal!!
Y_3 <- df_unbalance_redist_WGI[, "Giving_money"]
D_3 <- df_unbalance_redist_WGI[, "Relative_redistributive_effects"]
Z_3 <- df_unbalance_redist_WGI[, "Elderly_pct"]
Xname_3 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
  "y2011",
  "y2012",
  "y2013",
  "y2014",
  "y2015",
  "y2016",
  "y2017",
  "y2018"
)

X_3 <- df_unbalance_redist_WGI[, Xname_3]

#GINI_3_1_iv <- ivmodel(Y = Y_3, D = D_3, Z = Z_3, X = X_3)
#GINI_3_1_test <- AR.test(GINI_3_1_iv)



#GINI_3_1_LIML <- LIML(GINI_3_1_iv)


```





```{r , echo=FALSE, include=FALSE}
# 4. Public -Grants



df_unbalance_pub_grants <- df[!is.na(df$Public_transfer) &
  !is.na(df$Grants_by_private_agencies_and_NGOs) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Right_left) &
  !is.na(df$Elderly_pct) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Chrstprotpct), ]


df_unbalance_pub_grants_count <- df_unbalance_pub_grants %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_pub_grants_one <- df_unbalance_pub_grants_count[df_unbalance_pub_grants_count$count == 1, ]

for (i in df_unbalance_pub_grants_one$LOCATION) {
  df_unbalance_pub_grants <- df_unbalance_pub_grants[df_unbalance_pub_grants$LOCATION != i, ]
}

df_unbalance_pub_grants_timecount <- df_unbalance_pub_grants %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_pub_grants_timeone <- df_unbalance_pub_grants_timecount[df_unbalance_pub_grants_timecount$timecount == 1, ]


for (t in df_unbalance_pub_grants_timeone$TIME) {
  df_unbalance_pub_grants <- df_unbalance_pub_grants[df_unbalance_pub_grants$TIME != t, ]
}


###### pattern 1 - Eldery_pct

ivreg_unbalance_grants_pub_1 <- ivreg(Grants_by_private_agencies_and_NGOs ~ 1
+ Public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Estonia
  + Finland
  + Germany
  + Ireland
  + Italy
  + Republic_of_Korea
  + New_Zealand
  + Portugal
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 14 countries
  + y1992 # omit 1991
  + y1993
  + y1994
  + y1995
  + y1996
  + y1997
  + y1998
  + y1999
  + y2000
  + y2001
  + y2002
  + y2003
  + y2004
  + y2005
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + y2019 |
  . - Public_transfer
    + Elderly_pct,
data = df_unbalance_pub_grants
)

Public_4_1 <- coeftest(ivreg_unbalance_grants_pub_1, vcov = vcovHC, type = "HC3")





# abonrmal!!
Y_4 <- df_unbalance_pub_grants[, "Grants_by_private_agencies_and_NGOs"]
D_4 <- df_unbalance_pub_grants[, "Public_transfer"]
Z_4 <- df_unbalance_pub_grants[, "Elderly_pct"]
Xname_4 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
  "Austria",
  "Canada",
  "Estonia",
  "Finland",
  "Germany",
  "Ireland",
  "Italy",
  "Republic_of_Korea",
  "New_Zealand",
   "Portugal",
  "Switzerland",
  "Turkey",
  "United_Kingdom",
   "United_States_of_America",
 "y1992", # omit 1991
   "y1993",
   "y1994",
  "y1995",
  "y1996",
   "y1997",
   "y1998",
   "y1999",
  "y2000",
   "y2001",
   "y2002",
   "y2003",
   "y2004",
   "y2005",
   "y2006",
   "y2007",
   "y2008",
   "y2009",
   "y2010",
   "y2011",
   "y2012",
    "y2013",
   "y2014",
   "y2015",
   "y2016",
   "y2017",
   "y2018",
  "y2019"
)

X_4 <- df_unbalance_pub_grants[, Xname_4]

#Public_4_1_iv <- ivmodel(Y = Y_4, D = D_4, Z = Z_4, X = X_4)
#Public_4_1_test <- AR.test(Public_4_1_iv)



#Public_4_1_LIML <- LIML(Public_4_1_iv)
```


```{r , echo=FALSE, include=FALSE}


## 5. Public - log_Private


df_unbalance_priv_pub <- df[!is.na(df$Public_transfer) &
  !is.na(df$log_Private_transfer) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_priv_pub_count <- df_unbalance_priv_pub %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_priv_pub_one <- df_unbalance_priv_pub_count[df_unbalance_priv_pub_count$count == 1, ]

for (i in df_unbalance_priv_pub_one$LOCATION) {
  df_unbalance_priv_pub <- df_unbalance_priv_pub[df_unbalance_priv_pub$LOCATION != i, ]
}

df_unbalance_priv_pub_timecount <- df_unbalance_priv_pub %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_priv_pub_timeone <- df_unbalance_priv_pub_timecount[df_unbalance_priv_pub_timecount$timecount == 1, ]


for (t in df_unbalance_priv_pub_timeone$TIME) {
  df_unbalance_priv_pub <- df_unbalance_priv_pub[df_unbalance_priv_pub$TIME != t, ]
}



###### pattern 1 Elderly_pct

ivreg_unbalance_priv_pub_1 <- ivreg(log_Private_transfer ~ 1 + Public_transfer +
  +Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Lithuania
  + Luxembourg
  + Mexico
  + New_Zealand
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 25 countries
  + y1992 # omit 1991
  + y1993
  + y1994
  + y1995
  + y1996
  + y1997
  + y1998
  + y1999
  + y2000
  + y2001
  + y2002
  + y2003
  + y2004
  + y2005
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018 |
  . - Public_transfer
    + Elderly_pct,
data = df_unbalance_priv_pub
)

Public_5_1 <- coeftest(ivreg_unbalance_priv_pub_1, vcov = vcovHC, type = "HC3")



# abonrmal!!
Y_5 <- df_unbalance_priv_pub[, "log_Private_transfer"]
D_5 <- df_unbalance_priv_pub[, "Public_transfer"]
Z_5 <- df_unbalance_priv_pub[, "Elderly_pct"]
Xname_5 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
  # Australia
  #"Austria",
  #"Canada",
  #"Czech_Republic",
  #"Estonia",
  #"Finland",
  #"Germany",
  #"Hungary",
  #"Ireland",
  #"Israel",
  #"Italy",
  #"Lithuania",
  #"Luxembourg",
  #"Mexico",
  #"New_Zealand",
 # "Norway",
 # "Poland",
  #"Portugal",
 # "Republic_of_Korea",
  #"Slovakia",
  #"Slovenia",
 # "Switzerland",
 # "Turkey",
  #"United_Kingdom"
  # "United_States_of_America"
   "y1992", # omit 1991
   "y1993",
   "y1994",
   "y1995",
   "y1996",
   "y1997",
   "y1998",
   "y1999",
   "y2000",
   "y2001",
   "y2002",
   "y2003",
   "y2004",
   "y2005",
   "y2006",
   "y2007",
   "y2008",
   "y2009",
   "y2010",
   "y2011",
   "y2012",
   "y2013",
   "y2014",
   "y2015",
   "y2016",
   "y2017",
   "y2018"
)

X_5 <- df_unbalance_priv_pub[, Xname_5]

#Public_5_1_iv <- ivmodel(Y = Y_5, D = D_5, Z = Z_5, X = X_5)
#Public_5_1_test <- AR.test(Public_5_1_iv)



#Public_5_1_LIML <- LIML(Public_5_1_iv)




```


```{r , echo=FALSE, include=FALSE}
# 6. Public - WGI


df_unbalance_pub_WGI <- df[!is.na(df$Public_transfer) &
  !is.na(df$Giving_money) &
  (df$Giving_money != "") &
  (df$Giving_money != "-") &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Unemployment_rate_pct), ]

df_unbalance_pub_WGI <- df_unbalance_pub_WGI[df_unbalance_pub_WGI$Giving_money != "", ]

df_unbalance_pub_WGI_count <- df_unbalance_pub_WGI %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_pub_WGI_one <- df_unbalance_pub_WGI_count[df_unbalance_pub_WGI_count$count == 1, ]

for (i in df_unbalance_pub_WGI_one$LOCATION) {
  df_unbalance_pub_WGI <- df_unbalance_pub_WGI[df_unbalance_pub_WGI$LOCATION != i, ]
}

df_unbalance_pub_WGI_timecount <- df_unbalance_pub_WGI %>%
  group_by(TIME) %>%
  summarise(timecount = n())

df_unbalance_pub_WGI_timeone <- df_unbalance_pub_WGI_timecount[df_unbalance_pub_WGI_timecount$TIME == 1, ]

for (t in df_unbalance_pub_WGI_timeone$TIME) {
  df_unbalance_pub_WGI <- df_unbalance_pub_WGI[df_unbalance_pub_WGI$TIME != t, ]
}




###### pattern1 - Elederly_pct

ivreg_unbalance_pub_WGI_1 <- ivreg(Giving_money ~ 1
+ Public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Mexico
  + New_Zealand
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Turkey
  + United_Kingdom
  + United_States_of_America # 22 countries
  + y2011 # remove y2010  -9 years-
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018 |
  . - Public_transfer
    + Elderly_pct,
data = df_unbalance_pub_WGI
)

Public_6_1 <- coeftest(ivreg_unbalance_pub_WGI_1, vcov = vcovHC, type = "HC3")


# abonrmal!!
Y_6 <- df_unbalance_pub_WGI[, "Giving_money"]
D_6 <- df_unbalance_pub_WGI[, "Public_transfer"]
Z_6 <- df_unbalance_pub_WGI[, "Elderly_pct"]
Xname_6 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
  #+ Australia
  #"Austria",
  #"Canada",
  #"Czech_Republic",
  #"Estonia",
  #"Finland",
  #"Germany",
  #"Hungary",
  #"Ireland",
  #"Israel",
  #"Italy",
  #"Luxembourg",
  #"Mexico",
  #"New_Zealand",
  #"Poland",
  #"Portugal",
  #"Republic_of_Korea",
  #"Slovakia",
  #"Slovenia"
  #"Turkey"
 # "United_Kingdom"
  #"United_States_of_America"
   "y2011",
   "y2012",
   "y2013",
   "y2014",
   "y2015",
   "y2016",
   "y2017",
   "y2018"
)

X_6 <- df_unbalance_pub_WGI[, Xname_6]

Public_6_1_iv <- ivmodel(Y = Y_6, D = D_6, Z = Z_6, X = X_6)
Public_6_1_test <- AR.test(Public_6_1_iv)



Public_6_1_LIML <- LIML(Public_6_1_iv)


```


```{r , echo=FALSE, include=FALSE}


## 10. Net_public - grants

df_unbalance_netpub_grants <- df[!is.na(df$Net_public_transfer) &
  !is.na(df$Grants_by_private_agencies_and_NGOs) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_netpub_grants_count <- df_unbalance_netpub_grants %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_netpub_grants_one <- df_unbalance_netpub_grants_count[df_unbalance_netpub_grants_count$count == 1, ]

for (i in df_unbalance_netpub_grants_one$LOCATION) {
  df_unbalance_netpub_grants <- df_unbalance_netpub_grants[df_unbalance_netpub_grants$LOCATION != i, ]
}

df_unbalance_netpub_grants_timecount <- df_unbalance_netpub_grants %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_netpub_grants_timeone <- df_unbalance_netpub_grants_timecount[df_unbalance_netpub_grants_timecount$timecount == 1, ]


for (t in df_unbalance_netpub_grants_timeone$TIME) {
  df_unbalance_netpub_grants <- df_unbalance_netpub_grants[df_unbalance_netpub_grants$TIME != t, ]
}


##### pattern 1 - Elderly_pct

ivreg_unbalance_netpub_grants_1 <- ivreg(Grants_by_private_agencies_and_NGOs ~ 1 +
  Net_public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Finland
  + Germany
  + Ireland
  + Italy
  + Portugal
  + Republic_of_Korea
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 12 countries
  + y1997 # omit y1995
  + y1999
  + y2001
  + y2003
  + y2005
  + y2007
  + y2009
  + y2011
  + y2013
  + y2015
  + y2017 |
  . - Net_public_transfer
    + Elderly_pct,
data = df_unbalance_netpub_grants
)

Netpub_10_1 <- coeftest(ivreg_unbalance_netpub_grants_1, vcov = vcovHC, type = "HC3")


## 11. Net pub - log_Private



df_unbalance_netpub_priv <- df[!is.na(df$Net_public_transfer) &
  !is.na(df$log_Private_transfer) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_netpub_priv_count <- df_unbalance_netpub_priv %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_netpub_priv_one <- df_unbalance_netpub_priv_count[df_unbalance_netpub_priv_count$count == 1, ]

for (i in df_unbalance_netpub_priv_one$LOCATION) {
  df_unbalance_netpub_priv <- df_unbalance_netpub_priv[df_unbalance_netpub_priv$LOCATION != i, ]
}

df_unbalance_netpub_priv_timecount <- df_unbalance_netpub_priv %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_netpub_priv_timeone <- df_unbalance_netpub_priv_timecount[df_unbalance_netpub_priv_timecount$timecount == 1, ]


for (t in df_unbalance_netpub_priv_timeone$TIME) {
  df_unbalance_netpub_priv <- df_unbalance_netpub_priv[df_unbalance_netpub_priv$TIME != t, ]
}


##### pattern 1 - Elderly_pct

ivreg_unbalance_netpub_priv_1 <- ivreg(log_Private_transfer ~ 1 +
  Net_public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 21 countries
  + y1997 # omit y1995
  + y1999
  + y2001
  + y2003
  + y2005
  + y2007
  + y2009
  + y2011
  + y2013
  + y2015
  + y2017 |
  . - Net_public_transfer
    + Elderly_pct,
data = df_unbalance_netpub_priv
)

Netpub_11_1 <- coeftest(ivreg_unbalance_netpub_priv_1, vcov = vcovHC, type = "HC3")


## 12. Net Public - WGI



df_unbalance_netpub_WGI <- df[!is.na(df$Net_public_transfer) &
  !is.na(df$Giving_money) &
  (df$Giving_money != "") &
  (df$Giving_money != "-") &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_netpub_WGI_count <- df_unbalance_netpub_WGI %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_netpub_WGI_one <- df_unbalance_netpub_WGI_count[df_unbalance_netpub_WGI_count$count == 1, ]

for (i in df_unbalance_netpub_WGI_one$LOCATION) {
  df_unbalance_netpub_WGI <- df_unbalance_netpub_WGI[df_unbalance_netpub_WGI$LOCATION != i, ]
}

df_unbalance_netpub_WGI_timecount <- df_unbalance_netpub_WGI %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_netpub_WGI_timeone <- df_unbalance_netpub_WGI_timecount[df_unbalance_netpub_WGI_timecount$timecount == 1, ]


for (t in df_unbalance_netpub_WGI_timeone$TIME) {
  df_unbalance_netpub_WGI <- df_unbalance_netpub_WGI[df_unbalance_netpub_WGI$TIME != t, ]
}

##### pattern 1 - Elderly_pct

ivreg_unbalance_netpub_WGI_1 <- ivreg(Giving_money ~ 1 +
  Net_public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Turkey
  + United_Kingdom
  + United_States_of_America # 19 countries
  + y2013 # omit y2011
  + y2015
  + y2017 |
  . - Net_public_transfer
    + Elderly_pct,
data = df_unbalance_netpub_WGI
)

Netpub_12_1 <- coeftest(ivreg_unbalance_netpub_WGI_1, vcov = vcovHC, type = "HC3")
```





```{r, echo=FALSE,results='asis'}


stargazer(GINI_1_1, GINI_2_1, GINI_3_1, Public_4_1, Public_5_1, Public_6_1, Netpub_10_1, Netpub_11_1, Netpub_12_1,
  keep = c(
    "\\bRelative_redistributive_effects\\b", "\\bPublic_transfer\\b", "\\bNet_public_transfer\\b",
    "\\bUnemployment_rate_pct\\b", "\\bPoverty_rate\\b", "\\bChrstprotpct\\b", "\\bChrstcatpct\\b", "\\bChrstorthpct\\b", "\\bIslam_general_pct\\b", "\\bBuddism_general\\b"
  ),
  type = "html",
  title = "Regression: IV Estimation: Elderly rate",
  column.labels = c("Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index"),
  dep.var.caption = "Target variables",
  add.lines = list(
    c("Observations", nrow(df_unbalance_redist_grants), nrow(df_unbalance_redist_priv), nrow(df_unbalance_redist_WGI), nrow(df_unbalance_pub_grants), nrow(df_unbalance_priv_pub), nrow(df_unbalance_pub_WGI), nrow(df_unbalance_netpub_grants), nrow(df_unbalance_netpub_priv), nrow(df_unbalance_netpub_WGI)),
    c(
      "Countries", length(unique(df_unbalance_redist_grants$LOCATION)), length(unique(df_unbalance_redist_priv$LOCATION)), length(unique(df_unbalance_redist_WGI$LOCATION)), length(unique(df_unbalance_pub_grants$LOCATION)), length(unique(df_unbalance_priv_pub$LOCATION)), length(unique(df_unbalance_pub_WGI$LOCATION)),
      length(unique(df_unbalance_netpub_grants$LOCATION)), length(unique(df_unbalance_netpub_priv$LOCATION)), length(unique(df_unbalance_netpub_WGI$LOCATION))
    ),
    c(
      "Time Periods", length(unique(df_unbalance_redist_grants$TIME)), length(unique(df_unbalance_redist_priv$TIME)), length(unique(df_unbalance_redist_WGI$TIME)), length(unique(df_unbalance_pub_grants$TIME)), length(unique(df_unbalance_priv_pub$TIME)), length(unique(df_unbalance_pub_WGI$TIME)),
      length(unique(df_unbalance_netpub_grants$TIME)), length(unique(df_unbalance_netpub_priv$TIME)), length(unique(df_unbalance_netpub_WGI$TIME))
    )
  )
)
```

```{r, echo=FALSE,results='asis'}


stargazer(GINI_1_1, GINI_2_1, GINI_3_1, Public_4_1, Public_5_1, Public_6_1, Netpub_10_1, Netpub_11_1, Netpub_12_1,
  keep = c(
    "\\bRelative_redistributive_effects\\b", "\\bPublic_transfer\\b", "\\bNet_public_transfer\\b",
    "\\bUnemployment_rate_pct\\b", "\\bPoverty_rate\\b", "\\bChrstprotpct\\b", "\\bChrstcatpct\\b", "\\bChrstorthpct\\b", "\\bIslam_general_pct\\b", "\\bBuddism_general\\b"
  ),
  type = "latex",
  out = "c.IV-Elderly_pct_new.tex",
  title = "Regression: IV Estimation: Elderly rate",
  column.labels = c("Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index"),
  dep.var.caption = "Target variables",
  add.lines = list(
    c("Observations", nrow(df_unbalance_redist_grants), nrow(df_unbalance_redist_priv), nrow(df_unbalance_redist_WGI), nrow(df_unbalance_pub_grants), nrow(df_unbalance_priv_pub), nrow(df_unbalance_pub_WGI), nrow(df_unbalance_netpub_grants), nrow(df_unbalance_netpub_priv), nrow(df_unbalance_netpub_WGI)),
    c(
      "Countries", length(unique(df_unbalance_redist_grants$LOCATION)), length(unique(df_unbalance_redist_priv$LOCATION)), length(unique(df_unbalance_redist_WGI$LOCATION)), length(unique(df_unbalance_pub_grants$LOCATION)), length(unique(df_unbalance_priv_pub$LOCATION)), length(unique(df_unbalance_pub_WGI$LOCATION)),
      length(unique(df_unbalance_netpub_grants$LOCATION)), length(unique(df_unbalance_netpub_priv$LOCATION)), length(unique(df_unbalance_netpub_WGI$LOCATION))
    ),
    c(
      "Time Periods", length(unique(df_unbalance_redist_grants$TIME)), length(unique(df_unbalance_redist_priv$TIME)), length(unique(df_unbalance_redist_WGI$TIME)), length(unique(df_unbalance_pub_grants$TIME)), length(unique(df_unbalance_priv_pub$TIME)), length(unique(df_unbalance_pub_WGI$TIME)),
      length(unique(df_unbalance_netpub_grants$TIME)), length(unique(df_unbalance_netpub_priv$TIME)), length(unique(df_unbalance_netpub_WGI$TIME))
    )
  )
)
```









```{r, echo=FALSE,results='asis'}


#縦に並べる

#data <- matrix(c(
  #GINI_1_1_test$ci[1,1],
  #Public_4_1_test$ci[1,1],
  #GINI_1_1_test$ci[1,2],
  #Public_4_1_test$ci[1,2],
  #GINI_2_1_test$ci[1,1],
  #Public_5_1_test$ci[1,1],
  #GINI_2_1_test$ci[1,2],
  #Public_5_1_test$ci[1,2],
  #GINI_3_1_test$ci[1,1],
  #Public_6_1_test$ci[1,1],
  #GINI_3_1_test$ci[1,2],
  #Public_6_1_test$ci[1, 2]
#), 2, 6)



#colnames(data) <- c(
 # "----Grants by private agencies and NGOs lower---- ",
 # "----Grants by private agencies and NGOs upper---- ",
  #"log Private transfer lower",
  #"log Private transfer upper",
  #"----Giving money index lower----", "----Giving money index upper----"
#)

#rownames(data) <- c("Relative redistributive effects", "Public transfer")


#stargazer(data,
  #type = "html",
  #title = "AR test: Confidence Interval"
#)

#stargazer(data,
  #type = "latex",
  #title = "AR test: Confidence Interval"
#)




```






```{r, echo=FALSE,results='asis'}


#縦に並べる

#data_new <- matrix(c(
  #GINI_1_1_LIML$ci[1,1],
  #Public_4_1_LIML$ci[1,1],
  #GINI_1_1_LIML$ci[1,2],
  #Public_4_1_LIML$ci[1,2],
  #GINI_2_1_LIML$ci[1,1],
  #Public_5_1_LIML$ci[1,1],
  #GINI_2_1_LIML$ci[1,2],
  #Public_5_1_LIML$ci[1,2],
  #GINI_3_1_LIML$ci[1,1],
  #Public_6_1_LIML$ci[1,1],
  #GINI_3_1_LIML$ci[1,2],
  #Public_6_1_LIML$ci[1,2]
#), 2, 6)



#colnames(data_new) <- c(
  #"----Grants by private agencies and NGOs lower---- ",
  #"----Grants by private agencies and NGOs upper---- ",
  #"log Private transfer lower",
  #"log Private transfer upper",
  # "----Giving money index lower----", "----Giving money index upper----"
#)

#rownames(data_new) <- c("Relative redistributive effects", "Public transfer")


#stargazer(data_new,
  #type = "html",
  #title = "LIML:Confidence Interval"
#)

#stargazer(data_new,
  #type = "latex",
  #title = "LIML:Confidence Interval"
#)




```





```{r , echo=FALSE, include=FALSE}

df_unbalance_redist_priv$GINI <- df_unbalance_redist_priv$Relative_redistributive_effects
df_unbalance_redist_WGI$GINI <- df_unbalance_redist_WGI$Relative_redistributive_effects


df_unbalance_redist_priv$Absolute_GINI <-
(df_unbalance_redist_priv$GINI_before_taxes_and_transfers - df_unbalance_redist_priv$GINI_after_taxes_and_transfers)


df_unbalance_redist_WGI$Absolute_GINI <-
  (df_unbalance_redist_WGI$GINI_before_taxes_and_transfers - df_unbalance_redist_WGI$GINI_after_taxes_and_transfers)

write.csv(df_unbalance_redist_priv, "../Data/Unbalance_redist_priv.csv")
write.csv(df_unbalance_redist_WGI, "../Data/Unbalance_redist_WGI.csv")
write.csv(df_unbalance_priv_pub, "../Data/Unbalance_priv_pub.csv")
write.csv(df_unbalance_pub_WGI, "../Data/Unbalance_pub_WGI.csv")
write.csv(df_unbalance_netpub_priv, "../Data/Unbalance_netpub_priv.csv")
write.csv(df_unbalance_netpub_WGI, "../Data/Unbalance_netpub_WGI.csv")
```
