---
title: "Regression with IV: Elderly_pct, & Right_left"
author: Kanta Ogawa
date: "2022 / 03 / 15"
output: html_document
---



```{r read data, echo=FALSE, include=FALSE}
library(dplyr)
library(tidyr)
library(sandwich)
library(lmtest)
library(AER)
library(ggmap)
library(stargazer)
library(readr)
library(xtable)
library(ggplot2)
library(ivmodel)
# library(Hmisc)

df <- read.csv("../Data/panel_data.csv")

```



```{r, echo=FALSE, include=FALSE}

# 1. GINI - Grants

df_unbalance_redist_grants <- df[!is.na(df$Relative_redistributive_effects) &
  !is.na(df$Grants_by_private_agencies_and_NGOs) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Welfare_exp), ]

df_unbalance_redist_grants_count <- df_unbalance_redist_grants %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_redist_grants_one <- df_unbalance_redist_grants_count[df_unbalance_redist_grants_count$count == 1, ]

for (i in df_unbalance_redist_grants_one$LOCATION) {
  df_unbalance_redist_grants <- df_unbalance_redist_grants[df_unbalance_redist_grants$LOCATION != i, ]
}

df_unbalance_redist_grants_timecount <- df_unbalance_redist_grants %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK




###### pattern 5- all

ivreg_unbalance_rel_redist_grants_5 <- ivreg(Grants_by_private_agencies_and_NGOs ~ 1 + Relative_redistributive_effects
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Estonia
  + Finland
  + Germany
  + Ireland
  + Italy
  + New_Zealand
  + Portugal
  + Republic_of_Korea
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America
  + y2005 # omit y2004
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  +y2019 |
  . - Relative_redistributive_effects
  +Elderly_pct
  + Right_left,
data = df_unbalance_redist_grants
)

GINI_1_5 <- coeftest(ivreg_unbalance_rel_redist_grants_5, vcov = vcovHC, type = "HC3")

GINI_1_5_OR <- lm(residuals(ivreg_unbalance_rel_redist_grants_5) ~
   0
   +Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Estonia
  + Finland
  + Germany
  + Ireland
  + Italy
  + New_Zealand
  + Portugal
  + Republic_of_Korea
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America
  + y2005 # omit y2004
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + y2019
  +Elderly_pct
  + Right_left,
  data = df_unbalance_redist_grants)

GINI_1_5_test <- linearHypothesis(GINI_1_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


GINI_1_5_test_pvalue <- pchisq(GINI_1_5_test[2, 5], df = 1, lower.tail = FALSE)




# abonrmal!!
Y_1 <- df_unbalance_redist_grants[, "Grants_by_private_agencies_and_NGOs"]
D_1 <- df_unbalance_redist_grants[, "Relative_redistributive_effects"]
Z_1 <- df_unbalance_redist_grants[, c("Elderly_pct","Right_left")]
Xname_1 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
  "y2005",
  "y2006",
  "y2007",
  "y2008",
  "y2009",
  "y2010",
  "y2011",
  "y2012",
  "y2013",
  "y2014",
  "y2015",
  "y2016",
  "y2017",
  "y2018",
  "y2019"
)

X_1 <- df_unbalance_redist_grants[, Xname_1]

GINI_5_1_iv <- ivmodel(Y = Y_1, D = D_1, Z = Z_1, X = X_1)
GINI_5_1_test <- AR.test(GINI_5_1_iv)

GINI_5_1_LIML <- LIML(GINI_5_1_iv)


```


```{r, echo=FALSE, include=FALSE}
# 2. GINI - Private


df_unbalance_redist_priv <- df[!is.na(df$Relative_redistributive_effects) &
  !is.na(df$log_Private_transfer) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Right_left), ]

df_unbalance_redist_priv_count <- df_unbalance_redist_priv %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_redist_priv_one <- df_unbalance_redist_priv_count[df_unbalance_redist_priv_count$count == 1, ]

for (i in df_unbalance_redist_priv_one$LOCATION) {
  df_unbalance_redist_priv <- df_unbalance_redist_priv[df_unbalance_redist_priv$LOCATION != i, ]
}

df_unbalance_redist_priv_timecount <- df_unbalance_redist_priv %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_redist_priv_timeone <- df_unbalance_redist_priv_timecount[df_unbalance_redist_priv_timecount$timecount == 1, ]


for (t in df_unbalance_redist_priv_timeone$TIME) {
  df_unbalance_redist_priv <- df_unbalance_redist_priv[df_unbalance_redist_priv$TIME != t, ]
}



###### pattern 5 - all

ivreg_unbalance_rel_redist_priv_5 <- ivreg(log_Private_transfer ~ 1
+ Relative_redistributive_effects
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Lithuania
  + Luxembourg
  + Mexico
  + New_Zealand
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 25 countries
  + y2005 # omit y2004
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018 |
  . - Relative_redistributive_effects
  + Elderly_pct
  + Right_left,
data = df_unbalance_redist_priv
)


GINI_2_5 <- coeftest(ivreg_unbalance_rel_redist_priv_5, vcov = vcovHC, type = "HC3")






GINI_2_5_OR <- lm(residuals(ivreg_unbalance_rel_redist_priv_5) ~ 1
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Lithuania
  + Luxembourg
  + Mexico
  + New_Zealand
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 25 countries
  + y2005 # omit y2004
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + Elderly_pct
  + Right_left,
data = df_unbalance_redist_priv
)




GINI_2_5_test <- linearHypothesis(GINI_2_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


GINI_2_5_test_pvalue <- pchisq(GINI_2_5_test[2, 5], df = 1, lower.tail = FALSE)



# AR test


Y_2 <- df_unbalance_redist_priv[, "log_Private_transfer"]
D_2 <- df_unbalance_redist_priv[, "Relative_redistributive_effects"]
Z_2 <- df_unbalance_redist_priv[, c("Elderly_pct", "Right_left")]
Xname_2 <- c(
  "Poverty_rate",
  "Unemployment_rate_pct",
  "Chrstprotpct",
  "Chrstcatpct",
  "Chrstorthpct",
  "Islam_general_pct",
  "Buddism_general",
  "y2005", # omit y2004
  "y2006",
  "y2007",
  "y2008",
  "y2009",
  "y2010",
  "y2011",
  "y2012",
  "y2013",
  "y2014",
  "y2015",
  "y2016",
  "y2017",
  "y2018"

)

X_2 <- df_unbalance_redist_priv[, Xname_2]

GINI_2_5_iv <- ivmodel(Y = Y_2, D = D_2, Z = Z_2, X = X_2)
GINI_2_5_test <- AR.test(GINI_2_5_iv)








# 3. GINI - WGI


df_unbalance_redist_WGI <- df[!is.na(df$Relative_redistributive_effects) &
  !is.na(df$Giving_money) &
  (df$Giving_money != "") &
  (df$Giving_money != "-") &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Unemployment_rate_pct), ]

df_unbalance_redist_WGI <- df_unbalance_redist_WGI[df_unbalance_redist_WGI$Giving_money != "", ]

df_unbalance_redist_WGI_count <- df_unbalance_redist_WGI %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_redist_WGI_one <- df_unbalance_redist_WGI_count[df_unbalance_redist_WGI_count$count == 1, ]

for (i in df_unbalance_redist_WGI_one$LOCATION) {
  df_unbalance_redist_WGI <- df_unbalance_redist_WGI[df_unbalance_redist_WGI$LOCATION != i, ]
}

df_unbalance_redist_WGI_timecount <- df_unbalance_redist_WGI %>%
  group_by(TIME) %>%
  summarise(timecount = n())

df_unbalance_redist_WGI_timeone <- df_unbalance_redist_WGI_timecount[df_unbalance_redist_WGI_timecount$TIME == 1, ]

for (t in df_unbalance_redist_WGI_timeone$TIME) {
  df_unbalance_redist_WGI <- df_unbalance_redist_WGI[df_unbalance_redist_WGI$TIME != t, ]
}


###### pattern5-IV all

ivreg_unbalance_rel_redist_WGI_5 <- ivreg(Giving_money ~ 1 + Relative_redistributive_effects
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Mexico
  + New_Zealand
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Turkey
  + United_Kingdom
  + United_States_of_America # 23 countries
  + y2011 # remove y2010  -9 years-
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  +y2018 |
    . - Relative_redistributive_effects
  + Elderly_pct
  + Right_left,
data = df_unbalance_redist_WGI
)

GINI_3_5 <- coeftest(ivreg_unbalance_rel_redist_WGI_5, vcov = vcovHC, type = "HC3") # revise





# abnormal!!
GINI_3_5_OR <- lm(residuals(ivreg_unbalance_rel_redist_WGI_5) ~ 0
+Poverty_rate
+ Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  + Hungary
  +Ireland
  +Israel
  +Italy
  +Luxembourg
  +Mexico
  +New_Zealand
  +Poland
  +Portugal
  +Republic_of_Korea
  +Slovakia
  +Slovenia
  #+Turkey
  #+United_Kingdom
  #+United_States_of_America # 22 countries
  + y2011 # remove y2010  -9 years-
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  +y2018
  +Elderly_pct
  + Right_left,
data = df_unbalance_redist_WGI
)




GINI_3_5_test <- linearHypothesis(GINI_3_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


GINI_3_5_test_pvalue <- pchisq(GINI_3_5_test[2, 5], df = 1, lower.tail = FALSE)



```



```{r, echo=FALSE, include=FALSE}



# 4. Public - Grants



df_unbalance_pub_grants <- df[!is.na(df$Public_transfer) &
  !is.na(df$Grants_by_private_agencies_and_NGOs) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Right_left) &
  !is.na(df$Elderly_pct) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Chrstprotpct), ]


df_unbalance_pub_grants_count <- df_unbalance_pub_grants %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_pub_grants_one <- df_unbalance_pub_grants_count[df_unbalance_pub_grants_count$count == 1, ]

for (i in df_unbalance_pub_grants_one$LOCATION) {
  df_unbalance_pub_grants <- df_unbalance_pub_grants[df_unbalance_pub_grants$LOCATION != i, ]
}

df_unbalance_pub_grants_timecount <- df_unbalance_pub_grants %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_pub_grants_timeone <- df_unbalance_pub_grants_timecount[df_unbalance_pub_grants_timecount$timecount == 1, ]


for (t in df_unbalance_pub_grants_timeone$TIME) {
  df_unbalance_pub_grants <- df_unbalance_pub_grants[df_unbalance_pub_grants$TIME != t, ]
}

###### pattern 5- IV -all
ivreg_unbalance_grants_pub_5 <- ivreg(Grants_by_private_agencies_and_NGOs ~ 1
+ Public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Ireland
  + Italy
  + Republic_of_Korea
  + New_Zealand
  + Portugal
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 14 countries
  + y1992 # omit 1991
  + y1993
  + y1994
  + y1995
  + y1996
  + y1997
  + y1998
  + y1999
  + y2000
  + y2001
  + y2002
  + y2003
  + y2004
  + y2005
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + y2019 |
  . - Public_transfer
  + Elderly_pct
  + Right_left,
data = df_unbalance_pub_grants
)

Public_4_5 <- coeftest(ivreg_unbalance_grants_pub_5, vcov = vcovHC, type = "HC3")

Public_4_5_OR <- lm(residuals(ivreg_unbalance_grants_pub_5) ~ 1 +Poverty_rate
+ Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Ireland
  + Italy
  + Republic_of_Korea
  + New_Zealand
  + Portugal
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 14 countries
  + y1992 # omit 1991
  + y1993
  + y1994
  + y1995
  + y1996
  + y1997
  + y1998
  + y1999
  + y2000
  + y2001
  + y2002
  + y2003
  + y2004
  + y2005
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + y2019
  + Elderly_pct
  + Right_left,
data = df_unbalance_pub_grants)



Public_4_5_test <- linearHypothesis(Public_4_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


Public_4_5_test_pvalue <- pchisq(Public_4_5_test[2, 5], df = 1, lower.tail = FALSE)



## 5. Public - Private


df_unbalance_priv_pub <- df[!is.na(df$Public_transfer) &
  !is.na(df$log_Private_transfer) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_priv_pub_count <- df_unbalance_priv_pub %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_priv_pub_one <- df_unbalance_priv_pub_count[df_unbalance_priv_pub_count$count == 1, ]

for (i in df_unbalance_priv_pub_one$LOCATION) {
  df_unbalance_priv_pub <- df_unbalance_priv_pub[df_unbalance_priv_pub$LOCATION != i, ]
}

df_unbalance_priv_pub_timecount <- df_unbalance_priv_pub %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_priv_pub_timeone <- df_unbalance_priv_pub_timecount[df_unbalance_priv_pub_timecount$timecount == 1, ]


for (t in df_unbalance_priv_pub_timeone$TIME) {
  df_unbalance_priv_pub <- df_unbalance_priv_pub[df_unbalance_priv_pub$TIME != t, ]
}



##### pattern5 IV -all
ivreg_unbalance_priv_pub_5 <- ivreg(log_Private_transfer ~ 1 + Public_transfer +
  +Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Lithuania
  + Luxembourg
  + Mexico
  + New_Zealand
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 25 countries
  + y1992 # omit 1991
  + y1993
  + y1994
  + y1995
  + y1996
  + y1997
  + y1998
  + y1999
  + y2000
  + y2001
  + y2002
  + y2003
  + y2004
  + y2005
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018 |
  . - Public_transfer
   + Elderly_pct
  + Right_left,
data = df_unbalance_priv_pub
)

Public_5_5 <- coeftest(ivreg_unbalance_priv_pub_5, vcov = vcovHC, type = "HC3")




Public_5_5_OR <- lm(residuals(ivreg_unbalance_priv_pub_5) ~ 0
  +Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Lithuania
  + Luxembourg
  + Mexico
  + New_Zealand
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 25 countries
  + y1992 # omit 1991
  + y1993
  + y1994
  + y1995
  + y1996
  + y1997
  + y1998
  + y1999
  + y2000
  + y2001
  + y2002
  + y2003
  + y2004
  + y2005
  + y2006
  + y2007
  + y2008
  + y2009
  + y2010
  + y2011
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + Elderly_pct
  + Right_left,
data = df_unbalance_priv_pub
)



Public_5_5_test <- linearHypothesis(Public_5_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


Public_5_5_test_pvalue <- pchisq(Public_5_5_test[2, 5], df = 1, lower.tail = FALSE)







# 6. Public - WGI


df_unbalance_pub_WGI <- df[!is.na(df$Public_transfer) &
  !is.na(df$Giving_money) &
  (df$Giving_money != "") &
  (df$Giving_money != "-") &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate) &
  !is.na(df$Unemployment_rate_pct), ]

df_unbalance_pub_WGI <- df_unbalance_pub_WGI[df_unbalance_pub_WGI$Giving_money != "", ]

df_unbalance_pub_WGI_count <- df_unbalance_pub_WGI %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_pub_WGI_one <- df_unbalance_pub_WGI_count[df_unbalance_pub_WGI_count$count == 1, ]

for (i in df_unbalance_pub_WGI_one$LOCATION) {
  df_unbalance_pub_WGI <- df_unbalance_pub_WGI[df_unbalance_pub_WGI$LOCATION != i, ]
}

df_unbalance_pub_WGI_timecount <- df_unbalance_pub_WGI %>%
  group_by(TIME) %>%
  summarise(timecount = n())

df_unbalance_pub_WGI_timeone <- df_unbalance_pub_WGI_timecount[df_unbalance_pub_WGI_timecount$TIME == 1, ]

for (t in df_unbalance_pub_WGI_timeone$TIME) {
  df_unbalance_pub_WGI <- df_unbalance_pub_WGI[df_unbalance_pub_WGI$TIME != t, ]
}


###### pattern5 - all


ivreg_unbalance_pub_WGI_5 <- ivreg(Giving_money ~ 1
+ Public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Mexico
  + New_Zealand
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Turkey
  + United_Kingdom
  + United_States_of_America # 23countries
  + y2011 # remove y2010  -9 years-
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018 |
  . - Public_transfer
  + Elderly_pct
  + Right_left,
data = df_unbalance_pub_WGI
)

Public_6_5 <- coeftest(ivreg_unbalance_pub_WGI_5, vcov = vcovHC, type = "HC3")




Public_6_5_OR <- lm(residuals(ivreg_unbalance_pub_WGI_5) ~ 0 + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Australia
  + Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Mexico
  + New_Zealand
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  #+ Turkey
  #+ United_Kingdom
  #+ United_States_of_America # 23countries
  + y2011 # remove y2010  -9 years-
  + y2012
  + y2013
  + y2014
  + y2015
  + y2016
  + y2017
  + y2018
  + Elderly_pct
  + Right_left,
data = df_unbalance_pub_WGI
)




Public_6_5_test <- linearHypothesis(Public_6_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


Public_6_5_test_pvalue <- pchisq(Public_6_5_test[2, 5], df = 1, lower.tail = FALSE)


```


```{r, echo=FALSE, include=FALSE}


## 10. Net_public - grants



df_unbalance_netpub_grants <- df[!is.na(df$Net_public_transfer) &
  !is.na(df$Grants_by_private_agencies_and_NGOs) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_netpub_grants_count <- df_unbalance_netpub_grants %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_netpub_grants_one <- df_unbalance_netpub_grants_count[df_unbalance_netpub_grants_count$count == 1, ]

for (i in df_unbalance_netpub_grants_one$LOCATION) {
  df_unbalance_netpub_grants <- df_unbalance_netpub_grants[df_unbalance_netpub_grants$LOCATION != i, ]
}

df_unbalance_netpub_grants_timecount <- df_unbalance_netpub_grants %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_netpub_grants_timeone <- df_unbalance_netpub_grants_timecount[df_unbalance_netpub_grants_timecount$timecount == 1, ]


for (t in df_unbalance_netpub_grants_timeone$TIME) {
  df_unbalance_netpub_grants <- df_unbalance_netpub_grants[df_unbalance_netpub_grants$TIME != t, ]
}


##### pattern  5 - IV all

ivreg_unbalance_netpub_grants_5 <- ivreg(Grants_by_private_agencies_and_NGOs ~ 1 +
  Net_public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Finland
  + Germany
  #+ Greece
  + Ireland
  + Italy
  + Portugal
  + Republic_of_Korea
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 13 countries
  + y1997 # omit y1995
  + y1999
  + y2001
  + y2003
  + y2005
  + y2007
  + y2009
  + y2011
  + y2013
  + y2015
  + y2017 |
  . - Net_public_transfer
  + Elderly_pct
  + Right_left,
data = df_unbalance_netpub_grants
)

Netpub_10_5 <- coeftest(ivreg_unbalance_netpub_grants_5, vcov = vcovHC, type = "HC3")



Netpub_10_5_OR <- lm(residuals(ivreg_unbalance_netpub_grants_5) ~ 0 +
  Net_public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Finland
  + Germany
  #+ Greece
  + Ireland
  + Italy
  + Portugal
  + Republic_of_Korea
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 13 countries
  + y1997 # omit y1995
  + y1999
  + y2001
  + y2003
  + y2005
  + y2007
  + y2009
  + y2011
  + y2013
  + y2015
  + y2017
    + Elderly_pct
    + Right_left,
data = df_unbalance_netpub_grants
)



Netpub_10_5_test <- linearHypothesis(Netpub_10_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


Netpub_10_5_test_pvalue <- pchisq(Netpub_10_5_test[2, 5], df = 1, lower.tail = FALSE)






## 11. Net pub - Private



df_unbalance_netpub_priv <- df[!is.na(df$Net_public_transfer) &
  !is.na(df$log_Private_transfer) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_netpub_priv_count <- df_unbalance_netpub_priv %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_netpub_priv_one <- df_unbalance_netpub_priv_count[df_unbalance_netpub_priv_count$count == 1, ]

for (i in df_unbalance_netpub_priv_one$LOCATION) {
  df_unbalance_netpub_priv <- df_unbalance_netpub_priv[df_unbalance_netpub_priv$LOCATION != i, ]
}

df_unbalance_netpub_priv_timecount <- df_unbalance_netpub_priv %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_netpub_priv_timeone <- df_unbalance_netpub_priv_timecount[df_unbalance_netpub_priv_timecount$timecount == 1, ]


for (t in df_unbalance_netpub_priv_timeone$TIME) {
  df_unbalance_netpub_priv <- df_unbalance_netpub_priv[df_unbalance_netpub_priv$TIME != t, ]
}


##### pattern 5 - IV all

ivreg_unbalance_netpub_priv_5 <- ivreg(log_Private_transfer ~ 1 +
  Net_public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 22 countries
  + y1997 # omit y1995
  + y1999
  + y2001
  + y2003
  + y2005
  + y2007
  + y2009
  + y2011
  + y2013
  + y2015
  + y2017 |
  . - Net_public_transfer
  + Elderly_pct
  + Right_left,
data = df_unbalance_netpub_priv
)

Netpub_11_5 <- coeftest(ivreg_unbalance_netpub_priv_5, vcov = vcovHC, type = "HC3")




Netpub_11_5_OR <- lm(residuals(ivreg_unbalance_netpub_priv_5) ~ 0 + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Norway
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Switzerland
  + Turkey
  + United_Kingdom
  + United_States_of_America # 22 countries
  + y1997 # omit y1995
  + y1999
  + y2001
  + y2003
  + y2005
  + y2007
  + y2009
  + y2011
  + y2013
  + y2015
  + y2017
  + Elderly_pct
  + Right_left,
data = df_unbalance_netpub_priv
)



Netpub_11_5_test <- linearHypothesis(Netpub_11_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


Netpub_11_5_test_pvalue <- pchisq(Netpub_11_5_test[2, 5], df = 1, lower.tail = FALSE)







## 12. Net Public - WGI



df_unbalance_netpub_WGI <- df[!is.na(df$Net_public_transfer) &
  !is.na(df$Giving_money) &
  (df$Giving_money != "") &
  (df$Giving_money != "-") &
  !is.na(df$Chrstprotpct) &
  !is.na(df$Unemployment_rate_pct) &
  !is.na(df$Right_left) &
  !is.na(df$Poverty_rate), ]

df_unbalance_netpub_WGI_count <- df_unbalance_netpub_WGI %>%
  group_by(LOCATION) %>%
  summarise(count = n())

df_unbalance_netpub_WGI_one <- df_unbalance_netpub_WGI_count[df_unbalance_netpub_WGI_count$count == 1, ]

for (i in df_unbalance_netpub_WGI_one$LOCATION) {
  df_unbalance_netpub_WGI <- df_unbalance_netpub_WGI[df_unbalance_netpub_WGI$LOCATION != i, ]
}

df_unbalance_netpub_WGI_timecount <- df_unbalance_netpub_WGI %>%
  group_by(TIME) %>%
  summarise(timecount = n()) # each period is higher than 3 - OK

df_unbalance_netpub_WGI_timeone <- df_unbalance_netpub_WGI_timecount[df_unbalance_netpub_WGI_timecount$timecount == 1, ]


for (t in df_unbalance_netpub_WGI_timeone$TIME) {
  df_unbalance_netpub_WGI <- df_unbalance_netpub_WGI[df_unbalance_netpub_WGI$TIME != t, ]
}

##### pattern 5-

ivreg_unbalance_netpub_WGI_5<- ivreg(Giving_money ~ 1 +
  Net_public_transfer
  + Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  + Slovenia
  + Turkey
  + United_Kingdom
  + United_States_of_America # 20 countries
  + y2013 # omit y2011
  + y2015
  + y2017 |
  . - Net_public_transfer
  + Elderly_pct
  + Right_left,
data = df_unbalance_netpub_WGI
)

Netpub_12_5 <- coeftest(ivreg_unbalance_netpub_WGI_5, vcov = vcovHC, type = "HC3")



Netpub_12_5_OR <- lm(residuals(ivreg_unbalance_netpub_WGI_5) ~ 0 +  Poverty_rate
  + Unemployment_rate_pct
  + Chrstprotpct
  + Chrstcatpct
  + Chrstorthpct
  + Islam_general_pct
  + Buddism_general
  #+ Austria
  + Canada
  + Czech_Republic
  + Estonia
  + Finland
  + Germany
  #+ Greece
  + Hungary
  + Ireland
  + Israel
  + Italy
  + Luxembourg
  + Poland
  + Portugal
  + Republic_of_Korea
  + Slovakia
  #+ Slovenia
  #+ Turkey
  #+ United_Kingdom
  #+ United_States_of_America # 20 countries
  + y2013 # omit y2011
  + y2015
  + y2017
  + Elderly_pct
  + Right_left,
data = df_unbalance_netpub_WGI)



Netpub_12_5_test <- linearHypothesis(Netpub_12_5_OR,
  c("Elderly_pct =0", "Right_left = 0"),
  test = "Chisq"
)


Netpub_12_5_test_pvalue <- pchisq(Netpub_12_5_test[2, 5], df = 1, lower.tail = FALSE)


```



```{r, echo=FALSE,results='asis'}


stargazer(GINI_1_5, GINI_2_5, GINI_3_5, Public_4_5, Public_5_5, Public_6_5, Netpub_10_5, Netpub_11_5, Netpub_12_5,
  keep = c(
    "\\bRelative_redistributive_effects\\b", "\\bPublic_transfer\\b", "\\bNet_public_transfer\\b",
    "\\bUnemployment_rate_pct\\b", "\\bPoverty_rate\\b","\\bChrstprotpct\\b","\\bChrstcatpct\\b","\\bChrstorthpct\\b","\\bIslam_general_pct\\b","\\bBuddism_general\\b"
  ),
  type = "html",
  title = "Religion: IV Estimation: Elderly_pct & Right_left",
  column.labels = c("Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index"),
  dep.var.caption = "Target variables",
  add.lines = list(
    c("Observations", nrow(df_unbalance_redist_grants), nrow(df_unbalance_redist_priv), nrow(df_unbalance_redist_WGI), nrow(df_unbalance_pub_grants), nrow(df_unbalance_priv_pub), nrow(df_unbalance_pub_WGI), nrow(df_unbalance_netpub_grants), nrow(df_unbalance_netpub_priv), nrow(df_unbalance_netpub_WGI)),
    c(
      "Countries", length(unique(df_unbalance_redist_grants$LOCATION)), length(unique(df_unbalance_redist_priv$LOCATION)), length(unique(df_unbalance_redist_WGI$LOCATION)), length(unique(df_unbalance_pub_grants$LOCATION)), length(unique(df_unbalance_priv_pub$LOCATION)), length(unique(df_unbalance_pub_WGI$LOCATION)),
      length(unique(df_unbalance_netpub_grants$LOCATION)), length(unique(df_unbalance_netpub_priv$LOCATION)), length(unique(df_unbalance_netpub_WGI$LOCATION))
    ),
    c(
      "Time Periods", length(unique(df_unbalance_redist_grants$TIME)), length(unique(df_unbalance_redist_priv$TIME)), length(unique(df_unbalance_redist_WGI$TIME)), length(unique(df_unbalance_pub_grants$TIME)), length(unique(df_unbalance_priv_pub$TIME)), length(unique(df_unbalance_pub_WGI$TIME)),
      length(unique(df_unbalance_netpub_grants$TIME)), length(unique(df_unbalance_netpub_priv$TIME)), length(unique(df_unbalance_netpub_WGI$TIME))
    )
  )
)


```



```{r, echo=FALSE,results='asis'}


stargazer(GINI_1_5, GINI_2_5, GINI_3_5, Public_4_5, Public_5_5, Public_6_5, Netpub_10_5, Netpub_11_5, Netpub_12_5,
  keep = c(
    "\\bRelative_redistributive_effects\\b", "\\bPublic_transfer\\b", "\\bNet_public_transfer\\b",
    "\\bUnemployment_rate_pct\\b", "\\bPoverty_rate\\b","\\bChrstprotpct\\b","\\bChrstcatpct\\b","\\bChrstorthpct\\b","\\bIslam_general_pct\\b","\\bBuddism_general\\b"
  ),
  type = "latex",
  out = "../Code/g.IV-all.tex",
  title =  "Religion: IV Estimation: Elderly_pct & Right_left",
  column.labels = c("Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index", "Grants by private agencies and NGOs", "log Private transfer", "Giving money index"),
  dep.var.caption = "Target variables",
  add.lines = list(
    c("Observations", nrow(df_unbalance_redist_grants), nrow(df_unbalance_redist_priv), nrow(df_unbalance_redist_WGI), nrow(df_unbalance_pub_grants), nrow(df_unbalance_priv_pub), nrow(df_unbalance_pub_WGI), nrow(df_unbalance_netpub_grants), nrow(df_unbalance_netpub_priv), nrow(df_unbalance_netpub_WGI)),
    c(
      "Countries", length(unique(df_unbalance_redist_grants$LOCATION)), length(unique(df_unbalance_redist_priv$LOCATION)), length(unique(df_unbalance_redist_WGI$LOCATION)), length(unique(df_unbalance_pub_grants$LOCATION)), length(unique(df_unbalance_priv_pub$LOCATION)), length(unique(df_unbalance_pub_WGI$LOCATION)),
      length(unique(df_unbalance_netpub_grants$LOCATION)), length(unique(df_unbalance_netpub_priv$LOCATION)), length(unique(df_unbalance_netpub_WGI$LOCATION))
    ),
    c(
      "Time Periods", length(unique(df_unbalance_redist_grants$TIME)), length(unique(df_unbalance_redist_priv$TIME)), length(unique(df_unbalance_redist_WGI$TIME)), length(unique(df_unbalance_pub_grants$TIME)), length(unique(df_unbalance_priv_pub$TIME)), length(unique(df_unbalance_pub_WGI$TIME)),
      length(unique(df_unbalance_netpub_grants$TIME)), length(unique(df_unbalance_netpub_priv$TIME)), length(unique(df_unbalance_netpub_WGI$TIME))
    )
  )
)


```




# Overidentification test



```{r, echo=FALSE,results='asis'}
data <- matrix(c(GINI_1_5_test_pvalue, GINI_2_5_test_pvalue, GINI_3_5_test_pvalue, Public_4_5_test_pvalue, Public_5_5_test_pvalue, Public_6_5_test_pvalue, Netpub_10_5_test_pvalue, Netpub_11_5_test_pvalue, Netpub_12_5_test_pvalue), 3, 3)

colnames(data) <- c("----Grants by private agencies and NGOs---- ", "----Private transfer----", "----Giving money----")

rownames(data) <- c("Relative redistributive effects ", "Public transfer", "Net public transfer")




stargazer(data,
  type = "html",
  title = "IV Overidentification test : Elderly pct and Right-left of politics",
  notes = "columns: Target variables, rows: Explanatory variables"
)

stargazer(data,
type = "latex",
  title = "IV Overidentification test : Elderly pct and Right-left of politics",
  notes = "columns: Target variables, rows: Explanatory variables"
)

```
